Test CI config: use last working version from ttt-as1-rc1 and fix GRADLE_OPTS

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -28,6 +28,7 @@ env:
     - MOBI_MOD_NAME=android
     - WEAR_MOD_NAME=Wearable
     - LOG_TAGS='*:E'
+    - GRADLE_OPTS="-Xmx1024m -Dfile.encoding=UTF-8"
 
   matrix:
     - AVD_TARGET=android-15
@@ -37,42 +38,43 @@ env:
     - AVD_TARGET=android-19
     - AVD_TARGET=android-21
         AVD_PKGS=sys-img-armeabi-v7a-android-21
-    - AVD_TARGET=android-15 OPTS='-PdisablePreDex'
-    - AVD_TARGET=android-16 OPTS='-PdisablePreDex'
-    - AVD_TARGET=android-17 OPTS='-PdisablePreDex'
-    - AVD_TARGET=android-18 OPTS='-PdisablePreDex'
-    - AVD_TARGET=android-19 OPTS='-PdisablePreDex'
-    - AVD_TARGET=android-21 OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-15 GW_OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-16 GW_OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-17 GW_OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-18 GW_OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-19 GW_OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-21 GW_OPTS='-PdisablePreDex'
         AVD_PKGS=sys-img-armeabi-v7a-android-21
-    - AVD_TARGET='Google Inc.:Google APIs:21' OPTS='-PdisablePreDex' AVD_TAG=google_apis
+    - AVD_TARGET='Google Inc.:Google APIs:21' GW_OPTS='-PdisablePreDex' AVD_TAG=google_apis
         AVD_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-addon-google_apis-google-21
-    #- AVD_TARGET=android-21 AVD_ABI=x86 OPTS='-PdisablePreDex'
-    #- AVD_TARGET=android-21 AVD_ABI=x86_64 OPTS='-PdisablePreDex'
-    - AVD_TARGET=android-20 OPTS='-PdisablePreDex' AVD_TAG=android-wear
+    #- AVD_TARGET=android-21 AVD_ABI=x86 GW_OPTS='-PdisablePreDex'
+    #- AVD_TARGET=android-21 AVD_ABI=x86_64 GW_OPTS='-PdisablePreDex'
+    - AVD_TARGET=android-20 GW_OPTS='-PdisablePreDex' AVD_TAG=android-wear
 matrix:
   allow_failures:
-    #- env: AVD_TARGET=android-21 AVD_ABI=x86 OPTS='-PdisablePreDex'
-    #- env: AVD_TARGET=android-21 AVD_ABI=x86_64 OPTS='-PdisablePreDex'
-    - env: AVD_TARGET=android-20 OPTS='-PdisablePreDex' AVD_TAG=android-wear
+    #- env: AVD_TARGET=android-21 AVD_ABI=x86 GW_OPTS='-PdisablePreDex'
+    #- env: AVD_TARGET=android-21 AVD_ABI=x86_64 GW_OPTS='-PdisablePreDex'
+    - env: AVD_TARGET=android-20 GW_OPTS='-PdisablePreDex' AVD_TAG=android-wear
 
 notifications:
   email: false
 
 
 before_install:
-  - echo "EXPORT ENVIRONMENT VARIABLES";   export AVDT_DIR="$AVD_TARGET";
-      if [[ $AVD_TARGET == "Google Inc.:Google APIs:21" ]]; then AVDT_DIR="android-21"; fi;
-      if [[ "${OPTS:-}" == *-PdisablePreDex* ]]; then export PREDEX_OPT="-PdisablePreDex"; fi;
-      export GRADLE_OPTS="-Xmx1024m -Dfile.encoding=UTF-8 ${PREDEX_OPT:-}"
-      export MOD_NAME=`[[ $AVD_TAG = android-wear ]] && echo $WEAR_MOD_NAME || echo $MOBI_MOD_NAME`;
-      export AVD_NAME="${AVDT_DIR}-${AVD_TAG:-default}-${AVD_ABI:-armeabi-v7a}${PREDEX_OPT:-}";
-      export AVD_PATH="${TRAVIS_BUILD_DIR}/avds/${AVD_NAME:-test}"; mkdir avds; echo "$AVD_PATH";
+  - echo "EXPORT ENVIRONMENT VARIABLES"
+      export AVDT_DIR="$AVD_TARGET"
+      if [[ $AVD_TARGET == "Google Inc.:Google APIs:21" ]]; then AVDT_DIR="android-21"; fi
+      if [[ "${GW_OPTS:-}" == *-PdisablePreDex* ]]; then export PREDEX_OPT="-PdisablePreDex"; fi
+      export MOD_NAME=`[[ $AVD_TAG = android-wear ]] && echo $WEAR_MOD_NAME || echo $MOBI_MOD_NAME`
+      export AVD_NAME="${AVDT_DIR}-${AVD_TAG:-default}-${AVD_ABI:-armeabi-v7a}${PREDEX_OPT:-}"
+      export AVD_PATH="${TRAVIS_BUILD_DIR}/avds/${AVD_NAME:-test}"; mkdir avds; echo "$AVD_PATH"
       export IMG_PATH="${SDK}/system-images/${AVDT_DIR}/${AVD_TAG:-default}/${AVD_ABI:-armeabi-v7a}"
-  - echo "WARNING delete this when fixed"; export OLD_SDK=/usr/local/android-sdk-23.0.2;
-                                           mkdir -p ${SDK};
-                                           cp -u -R ${OLD_SDK}/platforms ${SDK}/platforms;
-                                           cp -u -R ${OLD_SDK}/system-images ${SDK}/system-images;
-                                           cp -u -R ${OLD_SDK}/tools ${SDK}/tools || echo "CP ERROR"
+  - echo "WARNING Update on 2014/12/09"
+      export OLD_SDK=/usr/local/android-sdk-23.0.2
+      mkdir -p ${SDK}
+      cp -u -R ${OLD_SDK}/platforms ${SDK}/platforms
+      cp -u -R ${OLD_SDK}/system-images ${SDK}/system-images
+      cp -u -R ${OLD_SDK}/tools ${SDK}/tools || echo "CP ERROR"
   - echo "LIST SUGGESTED SDK PACKAGES";    android list sdk -e || true
   - echo "INSTALL PACKAGES IF SUGGESTED";  echo y | android update sdk -u -t platform-tool,tool,\
                                            extra-android-support,extra-google-google_play_services,\
@@ -112,15 +114,15 @@ before_script:
   - echo "REDIRECT ADB LOGCAT TO A FILE";  adb -e logcat $LOG_TAGS | tee logcat.log>/dev/null 2>&1 &
 
 script:
-  #- echo "ASSEMBLE DEBUG BUILDS";          ./gradlew assembleDebug                   ${PREDEX_OPT:-}
-  #- echo "ASSEMBLE DEBUG TEST BUILDS";     ./gradlew assembleDebugTest               ${PREDEX_OPT:-}
-  #- echo "INSTALL MODULE DEBUG BUILD";     ./gradlew :${MOD_NAME:-app}:installDebug  ${PREDEX_OPT:-}
-  #- echo "INSTALL AND RUN DEBUG TESTS";    ./gradlew connectedAndroidTest            ${PREDEX_OPT:-}
-  #- echo "HANDLE RELEASE MICRO APK";       ./gradlew handleReleaseMicroApk           ${PREDEX_OPT:-}
-  #- echo "PREPARE RELEASE BUILDS";         ./gradlew generateReleaseSources          ${PREDEX_OPT:-}
-  #- echo "ASSEMBLE RELEASE BUILDS";        ./gradlew assembleRelease                 ${PREDEX_OPT:-}
-  - echo "ASSEMBLE AND TEST PROJECT";      ./gradlew ${MOD_NAME:-app}:build
-  - echo "RUN CONNECTED DEVICE CHECKS";    ./gradlew ${MOD_NAME:-app}:connectedCheck
+  #- echo "ASSEMBLE DEBUG BUILDS";          ./gradlew assembleDebug                   ${GW_OPTS:-}
+  #- echo "ASSEMBLE DEBUG TEST BUILDS";     ./gradlew assembleDebugTest               ${GW_OPTS:-}
+  #- echo "INSTALL MODULE DEBUG BUILD";     ./gradlew :${MOD_NAME:-app}:installDebug  ${GW_OPTS:-}
+  #- echo "INSTALL AND RUN DEBUG TESTS";    ./gradlew connectedAndroidTest            ${GW_OPTS:-}
+  #- echo "HANDLE RELEASE MICRO APK";       ./gradlew handleReleaseMicroApk           ${GW_OPTS:-}
+  #- echo "PREPARE RELEASE BUILDS";         ./gradlew generateReleaseSources          ${GW_OPTS:-}
+  #- echo "ASSEMBLE RELEASE BUILDS";        ./gradlew assembleRelease                 ${GW_OPTS:-}
+  - echo "ASSEMBLE AND TEST PROJECT";      ./gradlew ${MOD_NAME:-app}:build          ${GW_OPTS:-}
+  - echo "RUN CONNECTED DEVICE CHECKS";    ./gradlew ${MOD_NAME:-app}:connectedCheck ${GW_OPTS:-}
 
 after_success:
   - echo "SUCCESS!";                       echo "BUILD SUCCESSFUL"
