Update Travis config.....

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,23 +32,24 @@ env:
     - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
     - SDK=${TRAVIS_BUILD_DIR}/android-sdk
     - PATH=${GRADLE_USER_HOME}/bin/:${SDK}/:${SDK}/tools/:${SDK}/platform-tools/:${PATH}
+    - WFE_READY=${TRAVIS_BUILD_DIR}/scripts/wait_for_emulator.sh
     - BUILD_TOOLS='build-tools-21.1.1'
     - MOBI_MOD_NAME=android
     - WEAR_MOD_NAME=Wearable
-    - WFE_READY=${TRAVIS_BUILD_DIR}/scripts/wait_for_emulator.sh
+
 
   matrix:
    #- AVD_TARGET=android-15
    #- AVD_TARGET=android-16
-    - AVD_TARGET=android-17
+   #- AVD_TARGET=android-17
    #- AVD_TARGET=android-18
-   #- AVD_TARGET=android-19
-   #- AVD_TARGET=android-21
+    - AVD_TARGET=android-19
+    - AVD_TARGET=android-21
    #- AVD_TARGET=android-15 ARGS='-PdisablePreDex'
    #- AVD_TARGET=android-16 ARGS='-PdisablePreDex'
-   #- AVD_TARGET=android-17 ARGS='-PdisablePreDex'
+   # - AVD_TARGET=android-17 ARGS='-PdisablePreDex'
    #- AVD_TARGET=android-18 ARGS='-PdisablePreDex'
-   #- AVD_TARGET=android-19 ARGS='-PdisablePreDex'
+    - AVD_TARGET=android-19 ARGS='-PdisablePreDex'
     - AVD_TARGET=android-21 ARGS='-PdisablePreDex'
         AVD_PKGS=sys-img-armeabi-v7a-android-21
     - AVD_TARGET='Google Inc.:Google APIs:21' ARGS='-PdisablePreDex' AVD_TAG=google_apis
@@ -67,22 +68,20 @@ notifications:
 
 
 before_install:
-  - echo "EXPORT ENV VARIABLES";           export AVDT_DIR="$AVD_TARGET"
-  - if [[ $AVD_TARGET == "Google Inc.:Google APIs:21" ]]; then AVDT_DIR="android-21"; fi
-  - if [[ "${ARGS:-}" == *-PdisablePreDex* ]]; then export PREDEX_OPT="-PdisablePreDex"; fi
-  - export MOD_NAME=`[[ $AVD_TAG = android-wear ]] && echo $WEAR_MOD_NAME || echo $MOBI_MOD_NAME`
-  - export AVD_NAME="${AVDT_DIR}-${AVD_TAG:-default}-${AVD_ABI:-armeabi-v7a}${PREDEX_OPT:-}"
-  - export AVD_PATH="${TRAVIS_BUILD_DIR}/avds/${AVD_NAME:-test}"; mkdir avds; echo "$AVD_PATH"
-  - export IMG_PATH="${SDK}/system-images/${AVDT_DIR}/${AVD_TAG:-default}/${AVD_ABI:-armeabi-v7a}"
-
-  - echo "WARNING! delete when fixed";     export OLD_SDK=/usr/local/android-sdk-23.0.2
-  - cp -R ${OLD_SDK}/tools ${SDK}/tools || echo "SDK tools copy failed."
-  - cp -R ${OLD_SDK}/platforms ${SDK}/platforms || echo "SDK platforms copy failed."
-  - cp -R ${OLD_SDK}/system-images ${SDK}/system-images || echo "SDK system-images copy failed."
-
+  - echo "EXPORT ENVIRONMENT VARIABLES";   export AVDT_DIR="$AVD_TARGET";
+      if [[ $AVD_TARGET == "Google Inc.:Google APIs:21" ]]; then AVDT_DIR="android-21"; fi;
+      if [[ "${ARGS:-}" == *-PdisablePreDex* ]]; then export PREDEX_OPT="-PdisablePreDex"; fi;
+      export MOD_NAME=`[[ $AVD_TAG = android-wear ]] && echo $WEAR_MOD_NAME || echo $MOBI_MOD_NAME`;
+      export AVD_NAME="${AVDT_DIR}-${AVD_TAG:-default}-${AVD_ABI:-armeabi-v7a}${PREDEX_OPT:-}";
+      export AVD_PATH="${TRAVIS_BUILD_DIR}/avds/${AVD_NAME:-test}"; mkdir avds; echo "$AVD_PATH";
+      export IMG_PATH="${SDK}/system-images/${AVDT_DIR}/${AVD_TAG:-default}/${AVD_ABI:-armeabi-v7a}"
+  - echo "WARNING delete this when fixed"; export OLD_SDK=/usr/local/android-sdk-23.0.2;
+                                           mkdir ${SDK};
+                                           cp -R ${OLD_SDK}/platforms ${SDK}/platforms;
+                                           cp -R ${OLD_SDK}/system-images ${SDK}/system-images;
+                                           cp -R ${OLD_SDK}/tools ${SDK}/tools || echo "Copy failed"
   - echo "LIST SUGGESTED SDK PACKAGES";    android list sdk -e || true
-  - echo "LIST AVAILABLE SDK PACKAGES";    android list sdk -a -e || true
-  - echo "UPDATE PACKAGES IF REQUIRED";    echo y | android update sdk -u -t platform-tool,tool,\
+  - echo "INSTALL PACKAGES IF SUGGESTED";  echo y | android update sdk -u -t platform-tool,tool,\
                                            extra-android-support,extra-google-google_play_services,\
                                            extra-android-m2repository,extra-google-m2repository,\
                                            android-19,sys-img-armeabi-v7a-android-19,\
@@ -90,9 +89,10 @@ before_install:
                                            android-17,sys-img-armeabi-v7a-android-17,\
                                            android-16,sys-img-armeabi-v7a-android-16,\
                                            android-15,sys-img-armeabi-v7a-android-15 || true
-  - echo "UPDATE PACKAGES IF POSSIBLE";    echo y | android update sdk -a -u -t ${BUILD_TOOLS},\
+  - echo "LIST AVAILABLE SDK PACKAGES";    android list sdk -a -e || true
+  - echo "INSTALL PACKAGES IF AVAILABLE";  echo y | android update sdk -a -u -t ${BUILD_TOOLS},\
                                            android-20,android-21,${AVD_PKGS:-} || true
-  - echo "LIST SDK UPDATES BY FILTERS";    android update sdk -u -n -t platform,system-image,\
+  - echo "LIST FILTERED SDK PACKAGES";     android update sdk -u -n -t platform,system-image,\
                                            add-on,extra || true
 
 install:
@@ -105,10 +105,10 @@ install:
   - echo "START EMULATOR IN BACKGROUND";   emulator "@${AVD_NAME}" -no-skin -no-audio -no-window &
   - echo "WAIT FOR EMULATOR ONLINE";       adb wait-for-device
   - echo "DOWNLOAD GRADLE WRAPPER";        chmod +x ./gradlew; ls -l gradlew; ./gradlew -v
-  - echo "DOWNLOAD PROJECT DEPENDENCIES";  ./gradlew androidDependencies
-  - echo "CLEAN PROJECT";                  ./gradlew clean
-  - echo "PREPARE DEBUG AND DEBUG TEST";   ./gradlew generateDebugSources generateDebugTestSources
-  - echo "COMPILE DEBUG AND DEBUG TEST";   ./gradlew compileDebugSources compileDebugTestSources
+  #- echo "DOWNLOAD PROJECT DEPENDENCIES";  ./gradlew androidDependencies
+  #- echo "CLEAN PROJECT";                  ./gradlew clean
+  #- echo "PREPARE DEBUG AND DEBUG TEST";   ./gradlew generateDebugSources generateDebugTestSources
+  #- echo "COMPILE DEBUG AND DEBUG TEST";   ./gradlew compileDebugSources compileDebugTestSources
 
 before_script:
   - echo "WAIT FOR EMULATOR READY";        chmod +x $WFE_READY; ls -l $WFE_READY; $WFE_READY
@@ -116,12 +116,12 @@ before_script:
   - echo "REDIRECT ADB LOGCAT TO A FILE";  adb -e logcat *:W | tee logcat.log > /dev/null 2>&1 &
 
 script:
-  - echo "ASSEMBLE DEBUG BUILDS";          ./gradlew assembleDebug                  ${PREDEX_OPT:-}
-  - echo "ASSEMBLE DEBUG TEST BUILDS";     ./gradlew assembleDebugTest              ${PREDEX_OPT:-}
-  - echo "INSTALL MODULE DEBUG BUILD";     ./gradlew :${MOD_NAME:-app}:installDebug ${PREDEX_OPT:-}
-  - echo "INSTALL AND RUN DEBUG TESTS";    ./gradlew connectedAndroidTest           ${PREDEX_OPT:-}
-  - echo "PREPARE RELEASE BUILDS";         ./gradlew generateReleaseSources         ${PREDEX_OPT:-}
-  - echo "ASSEMBLE RELEASE BUILDS";        ./gradlew assembleRelease                ${PREDEX_OPT:-}
+  #- echo "ASSEMBLE DEBUG BUILDS";          ./gradlew assembleDebug                  ${PREDEX_OPT:-}
+  #- echo "ASSEMBLE DEBUG TEST BUILDS";     ./gradlew assembleDebugTest              ${PREDEX_OPT:-}
+  #- echo "INSTALL MODULE DEBUG BUILD";     ./gradlew :${MOD_NAME:-app}:installDebug ${PREDEX_OPT:-}
+  #- echo "INSTALL AND RUN DEBUG TESTS";    ./gradlew connectedAndroidTest           ${PREDEX_OPT:-}
+  #- echo "PREPARE RELEASE BUILDS";         ./gradlew generateReleaseSources         ${PREDEX_OPT:-}
+  #- echo "ASSEMBLE RELEASE BUILDS";        ./gradlew assembleRelease                ${PREDEX_OPT:-}
   - echo "ASSEMBLE AND TEST PROJECT";      ./gradlew build                          ${PREDEX_OPT:-}
   - echo "RUN CONNECTED DEVICE CHECKS";    ./gradlew connectedCheck                 ${PREDEX_OPT:-}
 
@@ -136,20 +136,21 @@ after_failure:
                                            WEAR_BUILD=${TRAVIS_BUILD_DIR}/${WEAR_MOD_NAME}/build/;
                                            DEBUG_INT=intermediates/tmp/dex/debug/inputList.txt;
                                            RELEASE_INT=intermediates/tmp/dex/release/inputList.txt;
-                                           LINT_OUTS=outputs/lint-results.html;
-                                           CONN=outputs/reports/androidTests/connected;
-                                           DEVICE=com.android.builder.testing.ConnectedDevice.html;
-                                           TEST_OUTS=com.android.builder.testing.testing.html;
-                                           apt-get install -qq lynx || true
+                                           LINT_LOG=outputs/lint-results.html;
+                                           CONNECTED_TMP=outputs/reports/androidTests/connected/;
+                                           TESTING_TMP=${CONNECTED_TMP}com.android.builder.testing.;
+                                           CONN_LOG=${TESTING_TMP}ConnectedDevice.html;
+                                           TEST_LOG=${TESTING_TMP}testing.html;
+                                           sudo apt-get install -qq lynx || true
   - echo "SHOW MOBI DEX INPUT LISTS";      cat ${MOBI_BUILD}${DEBUG_INT} ${MOBI_BUILD}${RELEASE_INT}
-  - echo "SHOW MOBI TEST AND LINT LOGS";   lynx --dump ${MOBI_BUILD}${LINT_OUTS} > mMobiLint.log;
-                                           lynx --dump ${MOBI_BUILD}${CONN_OUTS} > mMobiConnect.log;
-                                           lynx --dump ${MOBI_BUILD}${TEST_OUTS} > mMobiTesting.log;
+  - echo "SHOW MOBI TEST AND LINT LOGS";   lynx --dump ${MOBI_BUILD}${LINT_LOG} > mMobiLint.log;
+                                           lynx --dump ${MOBI_BUILD}${CONN_LOG} > mMobiConnect.log;
+                                           lynx --dump ${MOBI_BUILD}${TEST_LOG} > mMobiTesting.log;
                                            for file in mMobi*.log; do echo "$file";
                                            echo "====================="; cat "$file"; done || true
   - echo "SHOW WEAR DEX INPUT LISTS";      cat ${WEAR_BUILD}${DEBUG_INT} ${WEAR_BUILD}${RELEASE_INT}
-  - echo "SHOW WEAR TEST AND LINT LOGS";   lynx --dump ${WEAR_BUILD}${LINT_OUTS} > mWearLint.log;
-                                           lynx --dump ${WEAR_BUILD}${CONN_OUTS} > mWearConnect.log;
-                                           lynx --dump ${WEAR_BUILD}${TEST_OUTS} > mWearTesting.log;
+  - echo "SHOW WEAR TEST AND LINT LOGS";   lynx --dump ${WEAR_BUILD}${LINT_LOG} > mWearLint.log;
+                                           lynx --dump ${WEAR_BUILD}${CONN_LOG} > mWearConnect.log;
+                                           lynx --dump ${WEAR_BUILD}${TEST_LOG} > mWearTesting.log;
                                            for file in mWear*.log; do echo "$file";
                                            echo "====================="; cat "$file"; done || true
