Test dependencies....

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -76,10 +76,10 @@ before_install:
       export AVD_PATH="${TRAVIS_BUILD_DIR}/avds/${AVD_NAME:-test}"; mkdir avds; echo "$AVD_PATH";
       export IMG_PATH="${SDK}/system-images/${AVDT_DIR}/${AVD_TAG:-default}/${AVD_ABI:-armeabi-v7a}"
   - echo "WARNING delete this when fixed"; export OLD_SDK=/usr/local/android-sdk-23.0.2;
-                                           mkdir ${SDK};
-                                           cp -R ${OLD_SDK}/platforms ${SDK}/platforms;
-                                           cp -R ${OLD_SDK}/system-images ${SDK}/system-images;
-                                           cp -R ${OLD_SDK}/tools ${SDK}/tools || echo "Copy failed"
+                                           mkdir -p ${SDK};
+                                           cp -u -R ${OLD_SDK}/platforms ${SDK}/platforms;
+                                           cp -u -R ${OLD_SDK}/system-images ${SDK}/system-images;
+                                           cp -u -R ${OLD_SDK}/tools ${SDK}/tools || echo "CP ERROR"
   - echo "LIST SUGGESTED SDK PACKAGES";    android list sdk -e || true
   - echo "INSTALL PACKAGES IF SUGGESTED";  echo y | android update sdk -u -t platform-tool,tool,\
                                            extra-android-support,extra-google-google_play_services,\
@@ -121,7 +121,7 @@ script:
   #- echo "ASSEMBLE DEBUG TEST BUILDS";     ./gradlew assembleDebugTest              ${PREDEX_OPT:-}
   #- echo "INSTALL MODULE DEBUG BUILD";     ./gradlew :${MOD_NAME:-app}:installDebug ${PREDEX_OPT:-}
   #- echo "INSTALL AND RUN DEBUG TESTS";    ./gradlew connectedAndroidTest           ${PREDEX_OPT:-}
-  - echo "PREPARE RELEASE BUILDS";         ./gradlew generateReleaseSources         ${PREDEX_OPT:-}
+  #- echo "PREPARE RELEASE BUILDS";         ./gradlew generateReleaseSources         ${PREDEX_OPT:-}
   - echo "ASSEMBLE RELEASE BUILDS";        ./gradlew assembleRelease                ${PREDEX_OPT:-}
   - echo "ASSEMBLE AND TEST PROJECT";      ./gradlew build                          ${PREDEX_OPT:-} --info
   #- echo "RUN CONNECTED DEVICE CHECKS";    ./gradlew connectedCheck                 ${PREDEX_OPT:-}
